### ISSUE TITLE
The name 'Resource' does not exist in the current context

### ISSUE THREAD

**Issue by emrealtann** [Scandit/barcodescanner-sdk-xamarin-samples#3] opened 2017-05-26 11:22 UTC
`The name 'Resource' does not exist in the current context`
I get this error on "MainActivity.cs" file in Android project. Any suggestions?

**Comment by biasmv** [comment] 2017-05-26 12:17
Can you provide additional information on this issue? When are you getting this error? Does it happen during the build? If so, could you send us the complete build output? What version of Xamarin,  Mono.Android, Xamarin Studio, Visual Studio etc. are you using?

**Comment by emrealtann** [comment] 2017-05-26 13:50
@biasmv Yes, it happens during the build. Build is failing and giving this error two times:
![image](https://cloud.githubusercontent.com/assets/21173192/26497145/05134eae-4233-11e7-8682-198ce9cb128c.png)
I'm using Xamarin 4.4 and Visual Studio 2017. I didn't make any changes in your sample project.

**Comment by biasmv** [comment] 2017-05-29 08:33
The missing Resource symbol is is automatically generated by the Android/Xamarin build system during the build.  It's possible that you are seeing this because of some setup issue with your Android or Xamarin SDK. Sometimes these issues can also be resolved by cleaning the solution as well as removing any temporary files from the project folder, especially those in obj/bin folders.

We tried to reproduce the issue on our side. Unfortunately, we couldn't reproduce it. We are using a slightly more up-to-date version of Xamarin (4.5) together with the latest Visual Studio 2017 update. It's possible that updating to the latest Xamarin and Visual Studio resolves the issue for you.

**Comment by biasmv** [comment] 2017-06-14 15:12
There hasn't been an update on this for a while. Were you able to resolve the issue?

**Comment by emrealtann** [comment] 2017-06-15 07:00
Sorry, I was in a hurry and I've started to use another library for scanning.

**Comment by biasmv** [comment] 2017-06-15 07:20
No worries, I'll close the ticket then.

**Closed by biasmv** 2017-06-15 07:20 UTC
