### ISSUE TITLE
First run error

### ISSUE THREAD

**Issue by rgudgeon** [Scandit/barcodescanner-sdk-xamarin-samples#101] opened 2020-07-07 06:57 UTC
I down loaded Scandic today and installeg it on Visual Studio 2019. For a first run I loaded the simple Android sample and got the attached error.

I tried the Native Simple and got the same error.

Can you please have a look and see if I am doing anything wrong or if there is a problem at your end

Regards

Ray Gudgeon
Email:  ray.gudgeon@rga.com.au

![ScreenHunter_sacandic](https://user-images.githubusercontent.com/7763550/86731380-d163ba00-c072-11ea-8e60-fe3aca5a2d6c.jpg)

**Comment by petradonka** [comment] 2020-07-07 07:10
Hey @rgudgeon,

Thanks for reaching out! It looks like the problem is the package version you're specifying, `5.15.1.10` doesn't exist on NuGet, but `5.15.0.10` does exist, try with that version.
If you're still having issues, please reach out to support@scandit.com to help you resolve the issue you're having. I'll close this GitHub issue so our support team can take it over in case you need any further help.

Cheers,
Petra

**Closed by petradonka** 2020-07-07 07:10 UTC
