### ISSUE TITLE
SBSTextRecognitionSettings TextMode/OCR not working in Xamarin

### ISSUE THREAD

**Issue by victorarce** [Scandit/barcodescanner-sdk-xamarin-samples#73] opened 2019-02-27 19:09 UTC
Looks like the OCR text mode is not implemented in Xamarin. I tried native and forms.

**Comment by moritzhartmeier** [comment] 2019-03-01 11:52
Hi, OCR is not exposed in the unified library, it should however be available and working in the native components. Could you share with us how you tried to use it? We will have a look on our side as well that everything works as it should.

**Comment by victorarce** [comment] 2019-03-20 01:29
Hi, sorry for the long response. Yes, I supposed this was the case.  
TextRecognitionSettings is not accesible in forms, and in native it is, but its crashing. 

In this screenshot you can see that it crashes when setting recognition mode to text.  It also crashes when setting up to a new TestRecognitionSettings.  

I actually do need it in XF, but if it works on native, i can make it work on forms.  If there's a workaround, that will be great because I need to have a working POC before deciding to go with you guys.
Thanks for your time

![image](https://user-images.githubusercontent.com/11055018/54652378-eed2d600-4a73-11e9-8193-fd9988becfc8.png)

**Comment by lucatorella** [comment] 2019-03-20 14:41
Hey @victorarce, I checked our OCR sample and everything seems to work fine. You can find the sample in the `feature/textrecognition-sample` branch. 

I think that your problem is caused by the fact that you are using the default Scandit plugin from nuget.org which doesn't contain the OCR. In order to get the OCR build, you first need to contact sales, then you will be able to download the "special" OCR version.

**Comment by victorarce** [comment] 2019-03-20 21:43
The "special" OCR makes sense. I already filled the form, waiting for a sales person to contact me. Thanks

**Comment by victorarce** [comment] 2019-03-21 18:45
I downloaded  feature/textrecognition-sample but it wont work because im using nuget. Anyway, could you guys help me out to get a quote from sales? I filled out the form, and been waiting for them to contact me for a couple of days now. It's a bit frustrating not to know which OCR to use when you can't even test it or quote it.

**Comment by moritzhartmeier** [comment] 2019-03-22 12:11
I forwarded this to the sales department, I am sure someone will be in contact shortly.

**Closed** 2019-03-22 12:17 UTC
