### ISSUE TITLE
Support PCL 4.5 - Profile111

### ISSUE THREAD

**Issue by homerokzam** [Scandit/barcodescanner-sdk-xamarin-samples#1] opened 2016-12-02 11:54 UTC
I'm having problems when trying to install the package in a Xamarin.Forms project.

Here is the error:
Checking compatibility for Scandit.BarcodePicker.Unified 5.0.1 with .NETPortable,Version=v4.5,Profile=Profile111.
Package Scandit.BarcodePicker.Unified 5.0.1 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111). Package Scandit.BarcodePicker.Unified 5.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - net (.NETFramework,Version=v0.0)
  - uap10 (UAP,Version=v1.0)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios (Xamarin.iOS,Version=v0.0)

Thanks,
Homero

**Comment by biasmv** [comment] 2016-12-02 12:27
Hi,

I'm not sure I understand what's going on here. It's possible that the Windows 8 part is the problem. Could you try if removing support for Windows 8 (not 8.1) solves the issue for you? 

Best,
Marco

**Comment by biasmv** [comment] 2016-12-13 12:55
Have you been able to resolve the issue on your side? I'm closing the ticket, since there hasn't been any update on this in a while. If the problem persists, feel free to reopen it.

**Comment by homerokzam** [comment] 2016-12-15 08:46
I apologize for the delay, but I could not solve the problem.

I'm redoing the application and using the Scandit.BarcodePicker.Unified library. However I have the following error when trying to deploy to the device:

/Users/HomeroKzam/Projects/ParkCode/iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: SBSBarcodePicker. The symbol '_OBJC_CLASS_$_SBSBarcodePicker' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (ParkCode.iOS)

When I deploy to the simulator I have no problem compiling. I use Visual Studio for Mac.

Thanks,
Homero

**Comment by biasmv** [comment] 2016-12-15 08:50
Would it be possible to send us a project, so we can reproduce the issue on our side?

**Comment by homerokzam** [comment] 2016-12-15 09:20
Follow the link for the project.

https://github.com/homerokzam/PC

Thanks,
Homero

**Comment by biasmv** [comment] 2016-12-15 09:50
Great, thanks. We will take a look and get back to you.

**Comment by biasmv** [comment] 2016-12-15 16:12
Thanks for the project. We were able to reproduce the issue on our side. It appears to be specific issue with the project that you sent. Have you tried to create the project with Xamarin Studio instead of Visual Studio for Mac (VS for Mac is still in preview).

**Comment by biasmv** [comment] 2016-12-15 16:21
Also, make sure to update to the latest version of Xcode and Xamarin.iOS.

**Comment by homerokzam** [comment] 2016-12-15 16:26
I have not yet created the project using Xamarin Studio.
I'll do it now.

Thanks,
Homero

**Comment by antixaker** [comment] 2017-03-22 09:26
Hello!
I have a problem with using your component in Xamarin.Forms. Problems appear only for iOS project : during building I got 13 errors about native linking failed. These errors also appear when I try to build SimpleSample project for your component.
http://joxi.ru/Dr8OWG5UwLb7A6
Here is attached screenshot with errors.
Thanks, Alex

**Comment by biasmv** [comment] 2017-03-22 10:11
We have seen this happening when not using the latest version of Xcode. Did you update to the latest version (8.2.1)? Also make sure that Xamarin Studio and the iOS framework are completely up-to-date.

**Comment by antixaker** [comment] 2017-03-22 11:22
But I have the latest version of Xcode and iOS framework
Apple Developer Tools
Xcode 8.2.1 (11766.1)
Build 8C1002

Xamarin.iOS
Version: 10.4.0.128 (Xamarin Enterprise)
Hash: ba11e48
Branch: cycle9
Build date: 2017-03-10 08:48:04-0500

I think errors can be related to mono version. I have this version
Mono 4.8.0 (mono-4.8.0-branch/e4a3cf3) (64-bit)

**Comment by biasmv** [comment] 2017-03-23 16:14
Thanks for the update. We will take a look and get back to you.

**Comment by swenner** [comment] 2017-05-15 12:35
These errors are caused by the incremental build feature of Xamarin Studio. Please disable it for now.
More details: https://scandit.zendesk.com/hc/en-us/articles/115003233085-I-am-getting-error-Native-linking-failed-undefined-Objective-C-class-SBSBarcodePicker
Feel free to reopen the ticket if your issue still remains.

**Closed by swenner** 2017-05-15 12:35 UTC
